on: push
name: End to End Tests
jobs:
  mysql_test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: "my-secret-pw"
          MYSQL_DATABASE: "entpy"
        ports:
        - 3306
    steps:
    - uses: actions/checkout@master
    - name: run
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: test //e2e:mysql_test
  postgresql_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: "my-secret-pw"
          POSTGRES_DB: "entpy"
        ports:
        - 5432
    steps:
    - uses: actions/checkout@master
    - name: run
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: test //e2e:postgresql_test
  redis_test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
        - 6379
    steps:
    - uses: actions/checkout@master
    - name: run
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: test //e2e:redis_test
  sqlite_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: run
      uses: ngalaiko/bazel-action/1.2.1@master
      with:
        args: test //e2e:sqlite_test
